---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yash-app
  namespace: clone
  labels:
    app: yash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yash-app
  template:
    metadata:
      labels:
        app: yash-app
    spec:
      containers:
      - name: amazone-prime-container
        image: 200385945243.dkr.ecr.us-east-2.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
