---
apiVersion: v1
kind: Service
metadata:
  name: yash-app
  namespace: amazon
  labels:
    app: yash-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: yash-app
  type: LoadBalancer
...
